- group:    "[HW] Distbuild"
  start:    09-04-2020 18:00
  deadline: 30-04-2020 23:59
  tasks:
    - task: disttest
      score: 0

- group:    Reflect
  start:    16-04-2020 18:00
  deadline: 26-04-2020 23:59
  tasks:
    - task: reversemap
      score: 100
    - task: jsonlist
      score: 100
    - task: jsonrpc
      score: 100

- group:    Distbuild blocks
  start:    09-04-2020 18:00
  deadline: 23-04-2020 23:59
  tasks:
    - task: distbuild
      score: 300

- group:    HTTP and Context
  start:    02-04-2020 18:00
  deadline: 12-04-2020 23:59
  tasks:
    - task: firewall
      score: 100
    - task: wscat
      score: 100

- group:    Concurrency with shared memory
  start:    26-03-2020 18:00
  deadline: 05-04-2020 23:59
  tasks:
    - task: batcher
      score: 200
    - task: pubsub
      score: 300

- group:    Testing
  start:    19-03-2020 18:00
  deadline: 30-03-2020 23:59
  tasks:
    - task: tparallel
      score: 200
    - task: coverme
      score: 200
    - task: testequal
      score: 100

- group:    Goroutines
  start:    12-03-2020 18:00
  deadline: 23-03-2020 23:59
  tasks:
    - task: retryupdate
      score: 100
    - task: lrucache
      score: 100
    - task: externalsort
      score: 100
    - task: keylock
      score: 200

- group:    Interfaces
  start:    27-02-2020 18:00
  deadline: 08-03-2020 23:59
  tasks:
    - task: hotelbusiness
      score: 100
    - task: hogwarts
      score: 100
    - task: utf8
      score: 100
    - task: otp
      score: 100

- group:    Basics
  start:    20-02-2020 18:00
  deadline: 02-03-2020 23:59
  tasks:
    - task: digitalclock
      score: 300
    - task: urlshortener
      score: 200
    - task: olympics
      score: 300
    - task: varfmt
      score: 200

- group:    Hello World
  start:    12-02-2020 18:00
  deadline: 23-02-2020 23:59
  tasks:
    - task: sum
      score: 100
    - task: tour0
      score: 100
    - task: wordcount
      score: 100
    - task: urlfetch
      score: 100
    - task: fetchall
      score: 100
