- group:    Hello World
  start:    10-02-2022 18:00
  deadline: 20-02-2022 23:59
  tasks:
    - task: sum
      score: 100
    - task: tour0
      score: 100
    - task: wordcount
      score: 100
    - task: urlfetch
      score: 100
    - task: fetchall
      score: 100
