- group:    Testing
  start:    10-03-2022 20:00
  deadline: 29-03-2022 23:59
  tasks:
    - task: testequal
      score: 100
    - task: fileleak
      score: 100
    - task: tabletest
      score: 100
    - task: tparallel
      score: 200

- group:    Goroutines
  start:    03-03-2022 18:00
  deadline: 22-03-2022 23:59
  tasks:
    - task: tour1
      score: 100
    - task: once
      score: 100
    - task: rwmutex
      score: 100
    - task: waitgroup
      score: 100
    - task: cond
      score: 100
    - task: ratelimit
      score: 100

- group:    Interfaces
  start:    24-02-2022 18:00
  deadline: 13-03-2022 23:59
  tasks:
    - task: otp
      score: 100
    - task: lrucache
      score: 100
    - task: externalsort
      score: 100
    - task: retryupdate
      score: 100
    - task: ciletters
      score: 100

- group:    Basics
  start:    17-02-2022 18:00
  deadline: 06-03-2022 23:59
  tasks:
    - task: hotelbusiness
      score: 100
    - task: hogwarts
      score: 100
    - task: utf8
      score: 100
    - task: varfmt
      score: 100
    - task: speller
      score: 100
    - task: forth
      score: 100

- group:    Hello World
  start:    10-02-2022 18:00
  deadline: 20-02-2022 23:59
  tasks:
    - task: sum
      score: 100
    - task: tour0
      score: 100
    - task: wordcount
      score: 100
    - task: urlfetch
      score: 100
    - task: fetchall
      score: 100
